site_name: Lang Ya Shuai Notes
site_url: https://shuai-notes.vercel.app/
site_author: Lang Ya Shuai
site_description: Lang Ya Shuai Notes.

# repo_url: https://github.com/zhouushe/notes

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch Dark Mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: lime
      toggle:
        icon: material/lightbulb
        name: Switch Light Mode
  features:
    - navigation.instant    # Enable page switching without refreshing
    - navigation.tabs       # Use tab-style navigation
    - navigation.sections   # Group navigation items into sections
    - navigation.expand     # Expand all navigation levels
    - navigation.top        # Display a back-to-top button
    - search.highlight      # Highlight matching text in search results
    - content.code.annotate # Annotate code blocks in content
    - content.code.copy     # Add copy button
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/zhouushe/notes

nav:
  - Home: index.md
  - Jenkins:
      - Jenkins Script: jenkins_script.md
      - Jenkins Setup: jenkins_setup.md
  - K8S:
      - K8S Setup: k8s_setup.md
      - K8S Command: k8s_command.md
      - K8S FIO: k8s_fio.md
  - Redis:
      - Hot Data Cache: redis_hot_data_cache.md
      - Hybrid Storage: hybrid_storage.md
  - Python:
      - Decorator: python_decorator.md
      - Workflow: python_workflow.md
      - Dispatch: python_dispatch.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - fenced_code
  - tables
  - footnotes
  - meta
  - attr_list
  - pymdownx.highlight:
      linenums: true            # Enable line numbers
      anchor_linenums: true     # Make line numbers clickable
      line_spans: "__LINE__"    # Support line range markers
      pygments_lang_class: true # Add language class name
  - pymdownx.superfences

plugins:
  - search

extra_css:
  - css/custom.css
