name: Sensitive Words Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v4
      - name: Check Sensitive Words
        run: |
          python script/check_sensitive_words.py